version: '3.5'
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5434:5432  
      
  admin:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8080
