"""empty message

Revision ID: a0401d917b0a
Revises: 12112fcba105
Create Date: 2022-06-13 22:41:39.497749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0401d917b0a'
down_revision = '12112fcba105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_department', sa.String(length=200), nullable=False))
    op.drop_column('employee', 'employee_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employee', 'employee_department')
    # ### end Alembic commands ###
