"""empty message

Revision ID: a521df3d19ce
Revises: a852d496fa9a
Create Date: 2022-06-15 16:17:21.297493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a521df3d19ce'
down_revision = 'a852d496fa9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('check_in_selector', sa.Boolean(), nullable=True))
    op.add_column('attendance', sa.Column('check_out_selector', sa.Boolean(), nullable=True))
    op.alter_column('attendance', 'check_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'check_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('attendance', 'check_out_selector')
    op.drop_column('attendance', 'check_in_selector')
    # ### end Alembic commands ###
