"""empty message

Revision ID: 1635e29aa590
Revises: af18a4d0e64b
Create Date: 2022-06-17 14:38:39.454181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1635e29aa590'
down_revision = 'af18a4d0e64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('checked_in', sa.Boolean(), nullable=True))
    op.drop_column('employee', 'last_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('last_status', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('employee', 'checked_in')
    # ### end Alembic commands ###
