"""empty message

Revision ID: 12112fcba105
Revises: e480201537de
Create Date: 2022-06-13 21:39:03.169786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12112fcba105'
down_revision = 'e480201537de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
